default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres
  password: postgres
  host: localhost

development:
  <<: *default
  database: line_development

test:
  <<: *default
  database: line_test

production:
  <<: *default
  database: line_production
  username: postgres
  password: <%= ENV['DATABASE_PASSWORD'] %>
