name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: line_test

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - name: Install dependencies
        run: |
          gem install bundler:2.5.5
          bundle install --jobs 4 --retry 3
      - name: Set up database
        run: |
          cp config/database.yml.ci config/database.yml
          bin/rails db:create db:schema:load
      - name: Run tests
        run: bundle exec rspec
