name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: line_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      DATABASE_URL: "postgres://rails:password@localhost:5432/line_test"
      RAILS_ENV: test
      GITHUB_CLIENT_ID: ${{ secrets.GITHUB_CLIENT_ID }}
      GITHUB_CLIENT_SECRET: ${{ secrets.GITHUB_CLIENT_SECRET }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - name: Install dependencies
        run: |
          gem install bundler:2.5.5
          bundle install --jobs 4 --retry 3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install JavaScript dependencies
        run: npm install

      - name: Precompile assets
        env:
          RAILS_ENV: test
        run: |
          node build.ci.js

      - name: Set up database
        run: |
          mv config/database.ci.yml config/database.yml
          bin/rails db:create db:schema:load

      - name: Clear cache
        run: rm -rf tmp/cache

      - name: Run tests
        run: bundle exec rails test
